"use strict";
var encoder_1 = require('./encoder');
var regfile_1 = require('./regfile');
var t = new encoder_1.Encoder();
console.log(new Buffer(t.dec(regfile_1.r10d)));
console.log(new Buffer(t.mov_rm(regfile_1.eax, regfile_1.ebx)));
console.log(new Buffer(t.movq_r_r(regfile_1.rax, regfile_1.rax)));
console.log(new Buffer(t.movq_r_m(regfile_1.rax, regfile_1.rax.ref())));
console.log(new Buffer(t.movq_m_r(regfile_1.rbx.ref(), regfile_1.rax)));
console.log(new Buffer(t.movq_r_r(regfile_1.r12, regfile_1.r12)));
console.log(new Buffer(t.movq_m_r(regfile_1.r12.ref(), regfile_1.r12)));
console.log(new Buffer(t.movq_r_m(regfile_1.r12, regfile_1.r12.ref())));
