// Generated by CoffeeScript 1.10.0
(function() {
  var f_1;

  f_1 = function(argc, argv) {
    var l0, l1, l2;
    l0 = function() {
      var cmp;
      cmp = argc === 3;
      if (cmp) {
        return l1(l0);
      } else {
        return l2(l0);
      }
    };
    l1 = function() {
      l1.val1 = argv[1];
      l1.val2 = argv[2];
      l1.call1 = atoi(val1);
      l1.call2 = atoi(val2);
      l1.add = call1 + call2;
      return l2(l1);
    };
    l2 = function(phy) {
      l2.cval = -1;
      if (phy === l0) {
        l2.retval = l2.cval;
      }
      if (phy === l1) {
        l2.retval = l1.add;
      }
      return l2.retval;
    };
    return l0();
  };

  console.log(f_1(5));

}).call(this);
